export interface Flyer {
  id: string
  name: string
  category: string
  price: number
  priceType: "basic" | "regular" | "premium"
  hasPhotos: boolean
  imageUrl: string
  tags: string[]
  isRecentlyAdded?: boolean
  isFeatured?: boolean
}

export interface Category {
  id: string
  name: string
  slug: string
  description: string
  flyerCount: number
  imageUrl: string
}

export const FLYER_CATEGORIES: Category[] = [
  { id: "1", name: "Halloween", slug: "halloween", description: "Spooky Halloween party flyers", flyerCount: 245, imageUrl: "/halloween-category.jpg" },
  { id: "2", name: "Christmas", slug: "christmas", description: "Festive Christmas event flyers", flyerCount: 189, imageUrl: "/pic1.jpg" },
  { id: "3", name: "Valentine's", slug: "valentines", description: "Romantic Valentine's Day flyers", flyerCount: 156, imageUrl: "/pic2.jpg" },
  {
    id: "4",
    name: "Memorial Day",
    slug: "memorial-day",
    description: "Memorial Day celebration flyers",
    flyerCount: 98,
    imageUrl: "/pic3.jpg",
  },
  {
    id: "5",
    name: "President's Day",
    slug: "presidents-day",
    description: "President's Day event flyers",
    flyerCount: 67,
    imageUrl: "/pic4.jpg",
  },
  { id: "6", name: "Summer Parties", slug: "summer-parties", description: "Hot summer party flyers", flyerCount: 312, imageUrl: "/pic5.jpg" },
  { id: "7", name: "Neon Parties", slug: "neon-parties", description: "Bright neon party flyers", flyerCount: 178, imageUrl: "/pic6.jpg" },
  { id: "8", name: "Foam Parties", slug: "foam-parties", description: "Fun foam party flyers", flyerCount: 134, imageUrl: "/pic7.jpg" },
  { id: "9", name: "Ladies Night", slug: "ladies-night", description: "Ladies night event flyers", flyerCount: 223, imageUrl: "/pic1.jpg" },
  { id: "10", name: "Hookah Nights", slug: "hookah-nights", description: "Hookah lounge flyers", flyerCount: 167, imageUrl: "/pic2.jpg" },
  { id: "11", name: "Brunch", slug: "brunch", description: "Brunch event flyers", flyerCount: 145, imageUrl: "/pic3.jpg" },
  { id: "12", name: "EDM/DJs", slug: "edm-djs", description: "Electronic music and DJ flyers", flyerCount: 289, imageUrl: "/pic4.jpg" },
  { id: "13", name: "Game Night", slug: "game-night", description: "Game night event flyers", flyerCount: 112, imageUrl: "/pic5.jpg" },
  {
    id: "14",
    name: "Basic Flyers",
    slug: "basic-flyers",
    description: "Simple and clean flyer designs",
    flyerCount: 456,
    imageUrl: "/pic7.jpg",
  },
]

// Mock flyer data
export const SAMPLE_FLYERS: Flyer[] = [
  {
    id: "1",
    name: "Neon Nights Party",
    category: "Neon Parties",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic10.jpg",
    tags: ["neon", "party", "nightclub"],
    isRecentlyAdded: true,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Halloween Horror Night",
    category: "Halloween",
    price: 40,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic11.jpg",
    tags: ["halloween", "horror", "spooky"],
    isRecentlyAdded: false,
    isFeatured: true,
  },
  {
    id: "3",
    name: "Ladies Night Elegance",
    category: "Ladies Night",
    price: 10,
    priceType: "basic",
    hasPhotos: true,
    imageUrl: "/ladies-night-elegant-party-flyer.jpg",
    tags: ["ladies", "elegant", "nightclub"],
    isRecentlyAdded: false,
  },
  {
    id: "4",
    name: "EDM Festival Vibes",
    category: "EDM/DJs",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/edm-festival-electronic-music-flyer.jpg",
    tags: ["edm", "festival", "electronic"],
    isRecentlyAdded: true,
  },
  {
    id: "5",
    name: "Summer Beach Party",
    category: "Summer Parties",
    price: 40,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/summer-beach-party-tropical-flyer.jpg",
    tags: ["summer", "beach", "tropical"],
    isRecentlyAdded: false,
    isFeatured: true,
  },
  {
    id: "6",
    name: "Hookah Lounge Night",
    category: "Hookah Nights",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/hookah-lounge-middle-eastern-flyer.jpg",
    tags: ["hookah", "lounge", "relaxed"],
    isRecentlyAdded: false,
  },
  {
    id: "7",
    name: "Neon Nights Party",
    category: "Neon Parties",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/neon-party-flyer-dark-background.jpg",
    tags: ["neon", "party", "nightclub"],
    isRecentlyAdded: true,
    isFeatured: true,
  },
  {
    id: "8",
    name: "Spooky Haunted House",
    category: "Halloween",
    price: 25,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic32.jpg",
    tags: ["halloween", "haunted", "spooky"],
    isRecentlyAdded: true,
  },
  {
    id: "9",
    name: "Witches Night Out",
    category: "Halloween",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic28.jpg",
    tags: ["witches", "night", "party"],
    isRecentlyAdded: false,
  },
  {
    id: "10",
    name: "Christmas Wonderland",
    category: "Christmas",
    price: 20,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic21.jpg",
    tags: ["christmas", "holiday", "winter"],
    isRecentlyAdded: false,
    isFeatured: true,
  },
  {
    id: "11",
    name: "Santa's Holiday Party",
    category: "Christmas",
    price: 10,
    priceType: "basic",
    hasPhotos: true,
    imageUrl: "/pic41.jpg",
    tags: ["santa", "christmas", "celebration"],
    isRecentlyAdded: true,
  },
  {
    id: "12",
    name: "Romantic Valentine's Dinner",
    category: "Valentine's",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic39.jpg",
    tags: ["valentine", "romantic", "dinner"],
    isRecentlyAdded: false,
  },
  {
    id: "13",
    name: "Cupid's Dance Party",
    category: "Valentine's",
    price: 20,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic26.jpg",
    tags: ["valentine", "dance", "love"],
    isRecentlyAdded: false,
    isFeatured: true,
  },
  {
    id: "14",
    name: "Tropical Pool Bash",
    category: "Summer Parties",
    price: 30,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic23.jpg",
    tags: ["summer", "pool", "tropical"],
    isRecentlyAdded: false,
  },
  {
    id: "15",
    name: "Beach Bonfire Night",
    category: "Summer Parties",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic38.jpg",
    tags: ["summer", "beach", "party"],
    isRecentlyAdded: true,
  },
  {
    id: "16",
    name: "Glow in the Dark Rave",
    category: "Neon Parties",
    price: 25,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic25.jpg",
    tags: ["neon", "rave", "dance"],
    isRecentlyAdded: false,
  },
  {
    id: "17",
    name: "Neon Lights Extravaganza",
    category: "Neon Parties",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic37.jpg",
    tags: ["neon", "party", "nightclub"],
    isRecentlyAdded: false,
  },
  {
    id: "18",
    name: "Ultimate EDM Night",
    category: "EDM/DJs",
    price: 20,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic25.jpg",
    tags: ["edm", "dj", "festival"],
    isRecentlyAdded: false,
  },
  {
    id: "19",
    name: "Electronic Beats Party",
    category: "EDM/DJs",
    price: 25,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic41.jpg",
    tags: ["edm", "electronic", "music"],
    isRecentlyAdded: false,
    isFeatured: true,
  },
  {
    id: "20",
    name: "Glam Girls Night Out",
    category: "Ladies Night",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic34.jpg",
    tags: ["ladies", "night", "fun"],
    isRecentlyAdded: false,
  },
  {
    id: "21",
    name: "Ladies Lounge Party",
    category: "Ladies Night",
    price: 10,
    priceType: "basic",
    hasPhotos: true,
    imageUrl: "/pic38.jpg",
    tags: ["ladies", "lounge", "nightclub"],
    isRecentlyAdded: false,
  },
  {
    id: "22",
    name: "Mystic Hookah Lounge",
    category: "Hookah Nights",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "/pic40.jpg",
    tags: ["hookah", "lounge", "relax"],
    isRecentlyAdded: false,
  },
  {
    id: "23",
    name: "Hookah & Chill Night",
    category: "Hookah Nights",
    price: 20,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic31.jpg",
    tags: ["hookah", "chill", "night"],
    isRecentlyAdded: true,
  },
  {
    id: "24",
    name: "EDM Festival Vibes",
    category: "Brunch",
    price: 15,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "pic41.jpg",
    tags: ["edm", "festival", "electronic"],
    isRecentlyAdded: true,
  },
   {
    id: "25",
    name: "EDM Festival Vibes",
    category: "Brunch",
    price: 10,
    priceType: "regular",
    hasPhotos: true,
    imageUrl: "pic36.jpg",
    tags: ["edm", "festival", "electronic"],
    isRecentlyAdded: true,
  },
   {
    id: "26",
    name: "Board Game Night",
    category: "Game Night",
    price: 10,
    priceType: "basic",
    hasPhotos: true,
    imageUrl: "/pic33.jpg",
    tags: ["game", "board", "fun"],
    isRecentlyAdded: true,
    isFeatured: false,
  },
  {
    id: "27",
    name: "Video Game Tournament",
    category: "Game Night",
    price: 20,
    priceType: "premium",
    hasPhotos: true,
    imageUrl: "/pic22.jpg",
    tags: ["video", "game", "tournament"],
    isRecentlyAdded: false,
    isFeatured: true,
  },

]
